# -*- coding: utf-8 -*-
"""V10_Figure1_Propagation_v6.pdf and V10_Figure2_Scaling_Logic_v6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTH_FPJYTWB2Y0_XgnZJsSyjcDUt5JQS
"""

# ==============================================================================
# Project V10: ATP-Driven Quantum Order Verification
# Figures 1 & 2 Generation (v6 - Final Polish & Reviewer Compliant)
# Author: V10 Project Team (User & AI)
# Date: 2026-03-11
# ==============================================================================

import numpy as np
import matplotlib.pyplot as plt
import time

# --- 1. Publication-Ready Font Settings ---
plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['ps.fonttype'] = 42
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.size'] = 13 # Slightly larger for readability

# --- GPU Check ---
try:
    import cupy as cp
    xp = cp
except ImportError:
    xp = np

# ==============================================================================
# 2. Simulation Core (Same as v5)
# ==============================================================================
class SPGPE_Propagator:
    def __init__(self, L=100.0, N=64, T=0.05, dt=0.01, gamma=0.1):
        self.L = L; self.N = N; self.T = T; self.dt = dt; self.gamma = gamma
        self.dx = L / N
        self.x = xp.linspace(-L/2, L/2, N, endpoint=False)
        self.y = xp.linspace(-L/2, L/2, N, endpoint=False)
        self.z = xp.linspace(-L/2, L/2, N, endpoint=False)
        self.X, self.Y, self.Z = xp.meshgrid(self.x, self.y, self.z, indexing='ij')
        self.k = 2 * xp.pi * xp.fft.fftfreq(N, d=self.dx)
        self.KX, self.KY, self.KZ = xp.meshgrid(self.k, self.k, self.k, indexing='ij')
        self.K2 = self.KX**2 + self.KY**2 + self.KZ**2

        noise_scale = xp.sqrt(0.5 * T / (self.dx**3)) if T > 0 else 0.0
        self.psi = noise_scale * (xp.random.randn(N, N, N) + 1j * xp.random.randn(N, N, N))
        self.exp_K = xp.exp(-0.5j * self.dt * self.K2)
        self.is_crashed = False

    def apply_pulse(self, t, pulse_time=5.0, amplitude=50.0):
        if t < pulse_time:
            z0 = -self.L / 4.0
            width = 5.0
            return amplitude * xp.exp(-(self.Z - z0)**2 / (2 * width**2))
        return 0.0

    def step(self, t):
        if self.is_crashed: return
        V_ext = self.apply_pulse(t)
        density = xp.abs(self.psi)**2

        if xp.any(xp.isnan(density)) or xp.max(density) > 1e6:
            self.is_crashed = True
            return

        V_eff = V_ext - 1.0 * density
        op_V = -1j * (1 - 1j * self.gamma) * V_eff * self.dt
        self.psi *= xp.exp(op_V)
        self.psi = xp.fft.fftn(self.psi)
        op_K = -1j * (1 - 1j * self.gamma) * (self.K2 / 2) * self.dt
        self.psi *= xp.exp(op_K)
        self.psi = xp.fft.ifftn(self.psi)

        if self.T > 0:
            noise_amp = xp.sqrt(2 * self.gamma * self.T * self.dt / (self.dx**3))
            noise = noise_amp * (xp.random.randn(self.N, self.N, self.N) + 1j * xp.random.randn(self.N, self.N, self.N))
            self.psi += noise

    def get_z_profile(self):
        if self.is_crashed: return xp.full(self.N, xp.nan)
        return xp.sum(xp.abs(self.psi)**2, axis=(0, 1))

    def calculate_signal_contrast(self):
        if self.is_crashed: return 0.0
        z_profile = xp.sum(xp.abs(self.psi)**2, axis=(0, 1))
        target_profile = z_profile[int(3 * self.N / 4):]
        if len(target_profile) == 0: return 0.0
        peak, mean = xp.max(target_profile), xp.mean(target_profile)
        if mean == 0: return 0.0
        return float((peak / mean) - 1.0)

def run_scenario(scenario_name, T_val, steps=2000, dt=0.05):
    sim = SPGPE_Propagator(L=100.0, N=64, T=T_val, dt=dt, gamma=0.1)
    history = []
    for i in range(steps):
        sim.step(i * sim.dt)
        if i % 10 == 0:
            prof = sim.get_z_profile()
            history.append(cp.asnumpy(prof) if xp == cp else prof)
        if sim.is_crashed:
            for _ in range((steps - i) // 10): history.append(np.full(sim.N, np.nan))
            break
    return np.array(history), sim.calculate_signal_contrast()

# Run Data
data_A, cont_A = run_scenario("A", 0.0534, 2000, 0.05)
data_B, cont_B = run_scenario("B", 0.10, 10000, 0.01)
data_B_visual = data_B[::5]

# ==============================================================================
# 3. Figure 1: Energy Propagation
# ==============================================================================
fig1, axes = plt.subplots(1, 2, figsize=(14, 7), sharey=True)

# Safe strings requested by reviewer
left_title = f"Scenario A\nATP-scale low-noise regime\nT = 0.0534\nSignal contrast: C ≈ {cont_A:.2f}\n(more distinguishable)"
right_title = f"Scenario B\nHigh-noise reference regime\nT = 0.10\nSignal contrast: C ≈ {cont_B:.2f}\n(low distinguishability)"

im1 = axes[0].imshow(data_A, aspect='auto', origin='lower', cmap='magma', extent=[-50, 50, 0, 100])
axes[0].set_title(left_title, fontsize=13, fontweight='bold', pad=10)
axes[0].set_xlabel("Position $z$ (dimensionless)", fontsize=13)
axes[0].set_ylabel("Time (dimensionless)", fontsize=13)
axes[0].axvline(-25, color='white', linestyle='--', alpha=0.5)
axes[0].text(-23, 95, "Input pulse", color='white', fontsize=12, bbox=dict(facecolor='black', alpha=0.5, edgecolor='none'))

im2 = axes[1].imshow(data_B_visual, aspect='auto', origin='lower', cmap='magma', extent=[-50, 50, 0, 100])
axes[1].set_title(right_title, fontsize=13, fontweight='bold', pad=10)
axes[1].set_xlabel("Position $z$ (dimensionless)", fontsize=13)
axes[1].axvline(-25, color='white', linestyle='--', alpha=0.5)
axes[1].set_facecolor("grey")
axes[1].text(0, 75, "Outside validated\npre-crash window", color='white', fontsize=12, fontweight='bold', ha='center', va='center', bbox=dict(facecolor='black', alpha=0.5, edgecolor='none'))

cbar = fig1.colorbar(im2, ax=axes.ravel().tolist(), pad=0.02)
cbar.set_label("Energy density $|\psi|^2$", fontsize=13)

pdf1_name = "V10_Figure1_Propagation_v6.pdf"
plt.savefig(pdf1_name, bbox_inches='tight', format='pdf')
plt.close(fig1)

# ==============================================================================
# 4. Figure 2: Scaling Logic
# ==============================================================================
Tc = 0.0863
T_range = np.linspace(0.0, 0.14, 500)
m_ideal = np.zeros_like(T_range)
mask = T_range < Tc
m_ideal[mask] = (1 - T_range[mask]/Tc)**0.35
m_curve = m_ideal * (1 / (1 + np.exp((T_range - Tc)/0.005))) + 0.02 * (1 / (1 + np.exp((T_range - Tc)/0.005)))

fig2, ax = plt.subplots(figsize=(9, 6))

# Plot Curve
ax.plot(T_range, m_curve, color='black', linewidth=3)
ax.fill_between(T_range, 0, m_curve, color='gray', alpha=0.1)

# Tc Line
ax.axvline(Tc, color='gray', linestyle='--', linewidth=2)
ax.text(Tc + 0.002, 1.05, f'$T_c \\approx {Tc}$\n(Part IX estimate)', color='gray', fontsize=13, fontweight='bold', ha='left', va='top')

# Points (NO LEGEND, ONLY DIRECT ANNOTATION)
ax.scatter([0.0534], [order_parameter_model(np.array([0.0534]), Tc)[0] if 'order_parameter_model' in globals() else 0.73], color='green', s=200, zorder=10, edgecolors='black')
ax.text(0.0534 - 0.005, 0.55, "Scenario A\nATP-scale low-noise regime\n$T_{eff} \\approx 0.0534$", fontsize=12, color='green', fontweight='bold', ha='center', va='top')

ax.scatter([0.10], [0.0], color='red', s=200, zorder=10, edgecolors='black', marker='X')
ax.text(0.10 + 0.003, 0.15, "Scenario B\nHigh-noise reference regime\n$T = 0.10$", fontsize=12, color='red', fontweight='bold', ha='left', va='bottom')

# Scaling Box
scaling_label = "Scaling logic:\n$T_{eff} = k_B T_{phys} / E_{ATP}$\n$0.0267\\ eV / 0.5\\ eV \\approx 0.0534$"
ax.text(0.60, 0.65, scaling_label, transform=ax.transAxes, fontsize=12, verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

# Labels
ax.set_xlabel('Dimensionless temperature $T$', fontsize=14)
ax.set_ylabel('Order parameter $m(T)$ (schematic)', fontsize=14)
ax.set_xlim(0.0, 0.135)
ax.set_ylim(-0.05, 1.15)
ax.grid(True, linestyle=':', alpha=0.6)

pdf2_name = "V10_Figure2_Scaling_Logic_v6.pdf"
plt.savefig(pdf2_name, bbox_inches='tight', format='pdf')
plt.close(fig2)

print(f"✅ Generated {pdf1_name} and {pdf2_name}")

try:
    from google.colab import files
    files.download(pdf1_name)
    files.download(pdf2_name)
except ImportError:
    pass